### ISSUE TITLE
Error: Cannot find module '@/routes'のエラーの原因が分からない。

### ISSUE THREAD

**Issue by Frog-kt** [Frog-kt/online-voting#1]
# やりたいこと
import { registRoutes } from '@/routes';
↑
みたいにimport出来るようにしたい。

# 今の状態
エラー内容
```
Error: Cannot find module '@/routes'
Require stack:
- C:\Users\Nov\Documents\online-voting\src\app.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Nov\Documents\online-voting\src\app.ts:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\Users\Nov\Documents\online-voting\node_modules\.pnpm\ts-node@9.1.1_typescript@4.1.3\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Nov\Documents\online-voting\node_modules\.pnpm\ts-node@9.1.1_typescript@4.1.3\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

該当のコード
./src/app.ts
```typescript
import { registRoutes } from '@/routes';
app.use(registRoutes);
```

./src/routes/index.ts
```typescript
import { Express } from 'express';
import authRouter from './auth';

export function registRoutes(app: Express) {
  app.use('/api/v1/auth', authRouter);
}
```
./src/routes/auth.ts
```typescript
import { Router } from 'express';

const router = Router();

router.get('/', (req, res) => {
  res.status(200).send('OK'); // テスト
});

export default router;
```

**Comment by Frog-kt** [comment]
解決

tsconfig-paths/register が必要らしいです。
参考記事 [ts-node で実行時に tsconfig.json の paths(alias) 設定が効かない](https://qiita.com/nju33/items/e6be7f06b887ad662f1b)

これを参考に、package.jsonのscriptを以下のように書き換え

package.json
```JSON
{
  "scripts": {
    "dev": "nodemon --watch src --ext ts,js,json,graphql --exec ts-node -r tsconfig-paths/register src/app.ts"
  },
}
```

**Comment by hannoeru** [comment]
この問題は以前の会議で言ったよ、、
